#!/usr/bin/env bash
# 
# init dotfile setup aka set up gitmodule && and pull bics
#

echo "Installing curl and stow..."
sudo pacman -S curl stow

pushd "$PWD/git"
git submodule init
git submodule update
popd

# setup bics
if [[ ! -d ~/.bics ]]; then
	echo 'installing bics'
	pushd "$HOME"
	bash <(curl -sSL https://raw.githubusercontent.com/bahamas10/bics/master/bics) init
fi

