[[language]]
name = "go"
auto-format= true
diagnostic-severity = "hint"
formatter = { command = "goimports" }

[language-server.gopls]
command = "gopls"

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c", "h"]
comment-token = "//"
language-servers = [ "clangd" ]
indent = { tab-width = 2, unit = "  " }

[language-server.clangd]
command = "clangd"

[[language]]
name = "perl"
auto-format= true
formatter = { command = "perltidy", args = ["-l=80"] }
scope = "source.perl"
file-types = ["pl", "pm", "t", "psgi", "raku", "rakumod", "rakutest", "rakudoc", "nqp", "p6", "pl6", "pm6", { glob = "Rexfile" }]
shebangs = ["perl"]
comment-token = "#"
language-servers = [ "perlnavigator" ]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "bash"
scope = "source.bash"
injection-regex = "(shell|bash|zsh|sh)"
file-types = [
  "sh",
  "bash",
  "zsh",
  "zshenv",
  "zlogin",
  "zlogout",
  "zprofile",
  "zshrc",
  "eclass",
  "ebuild",
  "bazelrc",
  "Renviron",
  "zsh-theme",
  "ksh",
  "cshrc",
  "tcshrc",
  "bashrc_Apple_Terminal",
  "zshrc_Apple_Terminal",
  { glob = "*zshrc*" },
]
shebangs = ["sh", "bash", "dash", "zsh"]
comment-token = "#"
formatter = { command = "shfmt" }
language-servers = [ "bash-language-server" ]
indent = { tab-width = 2, unit = "  " }

[language-server]
bash-language-server = { command = "bash-language-server", args = ["start"] }

[[language]]
name = "git-commit"
rulers = [51, 73]
text-width = 72

