# Helix Language Server Configuration

[language.html]
roots = [".git", ".hg"]
language-server = { command = "vscode-html-language-server", args = ["--stdio"] }

[language.css]
roots = [".git", ".hg"]
language-server = { command = "vscode-css-language-server", args = ["--stdio"] }

[language.bash]
roots = [".git", ".hg"]
language-server = { command = "bash-language-server", args = ["start"] }

[language.go]
roots = [".git", "go.mod"]
language-server = { command = "gopls" }

[language.python]
roots = [".git", ".hg"]
language-server = { command = "pylsp" }

[language.lua]
roots = [".git", ".hg"]
language-server = { command = "lua-language-server" }

