[font]
normal = { family = "Terminus", style = "Regular" }
bold = { family = "Terminus", style = "Bold" }
italic = { family = "Terminus", style = "Italic" }
size = 14.0

[scrolling]
history = 42000
multiplier = 3

[shell]
program = "/bin/bash"
args = ["--login"]

[[key_bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[key_bindings]]
key = "C"
mods = "Control"
action = "Copy"

[[key_bindings]]
key = "Q"
mods = "Control"
action = "Quit"
